export const metadata = {
  title: "안녕하세요!",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <div>안녕하세요</div>
        {children}
      </body>
    </html>
  );
}
